FROM registry.access.redhat.com/ubi9/python-312 as build

USER 0
WORKDIR /app

COPY requirements.txt ./
RUN . /cachi2/cachi2.env && \
    pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml poetry.lock* README.md ./
COPY nemoguardrails/ ./nemoguardrails/
COPY examples/ ./examples/
COPY chat-ui/ ./chat-ui/
COPY scripts/provider-list.yaml ./scripts/
COPY scripts/filter_guardrails.py ./scripts/
COPY scripts/entrypoint.sh ./scripts/
RUN chmod +x ./scripts/entrypoint.sh

ARG GUARDRAILS_PROFILE=opensource
RUN python3 ./scripts/filter_guardrails.py ./scripts/provider-list.yaml $GUARDRAILS_PROFILE

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_NO_INTERACTION=1

RUN . /cachi2/cachi2.env && \
    poetry install --no-ansi --extras="sdd jailbreak openai nvidia tracing" && \
    poetry run pip install "spacy>=3.4.4,<4.0.0" && \
    poetry run pip install /cachi2/output/deps/generic/en_core_web_lg-3.7.1-py3-none-any.whl

FROM registry.access.redhat.com/ubi9/python-312

USER 0
WORKDIR /app

COPY --from=build /app /app
RUN rm -f /etc/security/namespace.conf /usr/lib64/security/pam_namespace.so || true && \
    chgrp -R 0 /app && \
    chmod -R g+rwX /app

USER 1001

ENV PATH="/app/.venv/bin:$PATH"
EXPOSE 8000
ENTRYPOINT ["./scripts/entrypoint.sh"]